### ISSUE TITLE
Fibonacci sequence

### ISSUE THREAD

**Issue by KennethLj** [Zewo/SwiftGo#2]
Great work!
I just wanted to point out that the output from the Fibonacci example shows 0,1,2,4,8,16... (2^N) instead of 1,1,2,3,5,8... as one would expect.

**Comment by paulofaria** [comment]
😱😱😱

I got that example from Go somewhere and didn't realize it wasn't actually fibonacci! Thanks a lot mate! Fixing it right now! I feel ashamed to miss this, haha.

😱😱😱

**Comment by paulofaria** [comment]
Actually the error was all mine. Go allows this:

```go
x, y = y, x+y
```

and in swift we have to do this:

```swift
z = x
x = y
y = z + y
```

**Comment by nvzqz** [comment]
Can't this also be achieved in Swift with tuples?
```swift
(x, y) = (y, x + y)
```

**Comment by paulofaria** [comment]
@nvzqz Indeed it can! Updated the example! Thanks mate!
